<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3yii2\d3notification\models\base;

use Yii;
use d3system\behaviors\D3DateTimeBehavior;

/**
 * This is the base-model class for table "d3n_notification".
 *
 * @property integer $id
 * @property integer $sys_company_id
 * @property string $time
 * @property integer $sys_model_id
 * @property integer $model_record_id
 * @property integer $key
 * @property integer $status_id
 * @property integer $type_id
 * @property string $data
 * @property string $notes
 *
 * @property \d3yii2\d3notification\models\D3nStatusHistory[] $d3nStatusHistories
 * @property \d3yii2\d3notification\models\D3nStatus $status
 * @property \d3yii2\d3notification\models\SysModels $sysModel
 * @property \d3yii2\d3notification\models\D3nType $type
 * @property string $aliasModel
 */
abstract class D3nNotification extends \d3system\models\D3ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return 'd3n_notification';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = [
        ];
        $behaviors = array_merge(
            $behaviors,
            D3DateTimeBehavior::getConfig(['time'])
        );
        return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            'required' => [['sys_company_id', 'sys_model_id', 'model_record_id', 'key', 'status_id'], 'required'],
            'tinyint Unsigned' => [['sys_model_id'],'integer' ,'min' => 0 ,'max' => 255],
            'smallint Unsigned' => [['sys_company_id','status_id','type_id'],'integer' ,'min' => 0 ,'max' => 65535],
            'integer Unsigned' => [['id','model_record_id','key'],'integer' ,'min' => 0 ,'max' => 4294967295],
            [['time'], 'safe'],
            [['data', 'notes'], 'string'],
            [['status_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d3yii2\d3notification\models\D3nStatus::className(), 'targetAttribute' => ['status_id' => 'id']],
            [['sys_model_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d3yii2\d3notification\models\SysModels::className(), 'targetAttribute' => ['sys_model_id' => 'id']],
            [['type_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d3yii2\d3notification\models\D3nType::className(), 'targetAttribute' => ['type_id' => 'id']],
            'D3DateTimeBehavior' => [['time_local'],'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('d3notification', 'ID'),
            'sys_company_id' => Yii::t('d3notification', 'Sys Company ID'),
            'time' => Yii::t('d3notification', 'Time'),
            'sys_model_id' => Yii::t('d3notification', 'Sys Model ID'),
            'model_record_id' => Yii::t('d3notification', 'Model Record ID'),
            'key' => Yii::t('d3notification', 'Key'),
            'status_id' => Yii::t('d3notification', 'Status ID'),
            'type_id' => Yii::t('d3notification', 'Type ID'),
            'data' => Yii::t('d3notification', 'Data'),
            'notes' => Yii::t('d3notification', 'Notes'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getD3nStatusHistories()
    {
        return $this->hasMany(\d3yii2\d3notification\models\D3nStatusHistory::className(), ['notification_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStatus()
    {
        return $this->hasOne(\d3yii2\d3notification\models\D3nStatus::className(), ['id' => 'status_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSysModel()
    {
        return $this->hasOne(\d3yii2\d3notification\models\SysModels::className(), ['id' => 'sys_model_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getType()
    {
        return $this->hasOne(\d3yii2\d3notification\models\D3nType::className(), ['id' => 'type_id']);
    }


    
    /**
     * @inheritdoc
     * @return \d3yii2\d3notification\models\D3nNotificationQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \d3yii2\d3notification\models\D3nNotificationQuery(get_called_class());
    }

}
